app/models.py
from datetime import datetime as dt
from app import db


class Department(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, nullable=False)
    employees = db.relationship('Employee', backref='department', lazy='dynamic')

    def __init__(self, name):
        self.name = name

class Employee(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    birthday = db.Column(db.Date, nullable=False)
    salary = db.Column(db.Integer, nullable=False)
    department_id = db.Column(db.Integer, db.ForeignKey('department.id'))

    def __init__(self, name, birthday, salary, department_id):
        self.name = name
        self.birthday = dt.strptime(birthday, '%Y-%m-%d').date()
        self.salary = salary
        self.department_id = department_id

# to create migration 'flask db init' (flask-migrate)
# to apply migration 'flask db migrate', 'flask db upgrade'

app/__init__.py
from flask import Flask
from config import Config, TestingConfig
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_restful import Api
import logging
from logging.handlers import RotatingFileHandler
import os



db = SQLAlchemy()
migrate = Migrate()


def create_app(testing=False):

    app = Flask(__name__)

    # testing mode (by default False)
    if testing:
        app.config.from_object(TestingConfig)

    else:
        app.config.from_object(Config)
        from app.models import Employee, Department
        db.init_app(app)
        migrate.init_app(app, db)

    from app.site import bp as site_bp
    app.register_blueprint(site_bp)
    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)
    from app.rest import bp as rest_bp

    if not app.debug and not app.testing:
        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/departments_app_DEBUG.log', maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.DEBUG)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.DEBUG)
        app.logger.info('departments_app')

    from app.rest.api import EmployeeApi, EmployeeByIdApi, DepartmentApi, DepartmentByIdApi, SearchApi, SearchByDepartmentApi

    restServ = Api(app)
    restServ.add_resource(EmployeeApi, '/api/employees')
    restServ.add_resource(EmployeeByIdApi, '/api/employees/<int:empl_id>')
    restServ.add_resource(DepartmentApi, '/api/departments')
    restServ.add_resource(DepartmentByIdApi, '/api/departments/<int:dep_id>')
    restServ.add_resource(SearchApi, '/api/search')
    restServ.add_resource(SearchByDepartmentApi, '/api/search/<int:dep_id>')

    return app

from app import models

app/rest/__init__.py
from flask import Blueprint

bp = Blueprint('rest', __name__)

from app.rest import api

app/site/__init__.py
from flask import Blueprint

bp = Blueprint('site', __name__)

from app.site import views

app/site/views.py
import requests
from flask import render_template, request, redirect, url_for, flash
from app.models import Department, Employee
from . import bp

# ========= SUPPLEMENTARY =========

BASE = 'http://localhost:5000'


# ========== API REQUESTS FUNCTIONS ============

def get_all_departments():
    """
    :return: departments data in json format. Keys: {id', 'name', 'employees', 'average_salary'}
    """
    return requests.get(f'{BASE}/api/departments').json()


def get_department_employees(dep_name):
    """
    :return: employees data in json format. Keys: {'id', 'name', 'birthday', 'salary', 'department_id}
    """
    dep_id = Department.query.filter_by(name=dep_name).first_or_404().id
    return requests.get(f'{BASE}/api/departments/{dep_id}').json()['employees']


def get_employee(empl_id):
    """
    :return: employee data in json format. Keys: {'id', 'name', 'birthday', 'salary', 'department_id'}
    """
    return requests.get(f'{BASE}/api/employees/{empl_id}').json()


def dep_name_by_empl_id(empl_id):
    dep_id = Employee.query.filter_by(id=empl_id).first_or_404().department_id
    return Department.query.filter_by(id=dep_id).first_or_404().name


# ========= DEPARTMENTS VIEWS FUNCTIONS ==============

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/departments', methods=['GET', 'POST'])
def departments():
    if request.method == 'GET':
        departments = get_all_departments()
        return render_template('departments.html', title="Dunder Mifflin Paper Company Inc. Scranton Branch",
                               departments=departments)
    elif request.method == 'POST':
        data = request.form
        requests.post(f'{BASE}/api/departments', data)
        flash('Department added')
    return redirect(url_for('site.departments'), 303)


@bp.route('/delete_department/<int:dep_id>')
def delete_department(dep_id):
    requests.delete(f'{BASE}/api/departments/{dep_id}')
    flash('Department deleted')
    return redirect(url_for('site.departments'), 303)


@bp.route('/update_department/<int:dep_id>', methods=['POST'])
def update_department(dep_id):
    data = request.form
    requests.put(f'{BASE}/api/departments/{dep_id}', data)
    flash('Department updated')
    return redirect(url_for('site.departments'), 303)


# ================== EMPLOYEES VIEW FUNCTIONS ====================

@bp.route('/departments/<string:dep_name>', methods=['GET', 'POST'])
def department(dep_name):
    if request.method == 'GET':
        dep_id = Department.query.filter_by(name=dep_name).first_or_404().id
        employees = get_department_employees(dep_name)
        departments = get_all_departments()
        return render_template('department.html', dep_name=dep_name, dep_id=dep_id, title=dep_name,
                               employees=employees, departments=departments)
    elif request.method == 'POST':
        data = request.form
        print(data)
        requests.post(f'{BASE}/api/employees', data)
        return redirect(url_for('site.department', dep_name=dep_name), 303)


@bp.route('/update_employee/<string:empl_id>', methods=['POST'])
def update_employee(empl_id):
    dep_name = dep_name_by_empl_id(empl_id)
    data = request.form
    requests.put(f'{BASE}/api/employees/{empl_id}', data)
    flash('Employee information updated')
    return redirect(url_for('site.department', dep_name=dep_name), 303)


@bp.route('/delete_employee/<int:empl_id>')
def delete_employee(empl_id):
    dep_name = dep_name_by_empl_id(empl_id)
    requests.delete(f'{BASE}/api/employees/{empl_id}')
    flash('Employee deleted')
    return redirect(url_for('site.department', dep_name=dep_name), 303)


@bp.route('/employees/<int:empl_id>')
def employee(empl_id):
    departments = get_all_departments()
    empl = get_employee(empl_id)
    dep_name = dep_name_by_empl_id(empl_id)
    return render_template('employee.html', dep_name=dep_name, title=empl['name'], empl=empl, departments=departments)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">

    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

app/templates/department.html
{% extends 'base.html' %}
{% include 'navbar.html' %}

{% block content %}

    <!--========FLEXBOX CONTAINER==========-->
    <div class="flexbox_container">

        <!-- 'ADD EMPLOYEE' FLEXBOX -->
        <a href='' class="flexbox_item btn-lg btn-success" data-toggle="modal" data-target="#modal_add_employee"
           style="justify-content: center; opacity: 0.5;">
            <div class="flexbox_inscription">
                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-plus" fill="currentColor"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M8 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10zM13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                </svg>
            </div>
        </a>

        <!-- 'EMPLOYEE' FLEXBOXES -->
        {% for empl in employees %}
            <div class="flexbox_item">
                <a href="{{ url_for('site.employee', empl_id=empl['id']) }}"
                   class="flexbox_inscription btn btn-lnk btn-sm">{{ empl['name'] }}</a>
                <div class="flexbox_subscription">
                    &#127874;{{ empl['birthday'] }};
                    &#128178;{{ empl['salary'] }}
                </div>

                <div class="flexbox_button">
                    <a type="button" class="btn btn-outline-success btn-sm"
                       data-toggle="modal" data-target="#modal_edit_employee{{ empl['id'] }}">Edit
                    </a>
                    <a href="{{ url_for('site.delete_employee', empl_id=empl['id']) }}"
                       class="btn btn-outline-danger btn-sm"
                       onclick="return confirm('Are you sure? All employee information will be deleted')">Delete</a>
                </div>
            </div>

            {% include 'modal_edit_employee.html' %}

        {% endfor %}
        {% include 'modal_add_employee.html' %}
    </div>

    <!-- ========== SEARCH DEPARTMENT EMPLOYEES BY BIRTHDAY ============= -->
    <button type="button" class="btn btn-secondary btn-circle btn-xl" data-toggle="modal"
            data-target="#modal_search_department_employees">
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
             xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
                  d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
            <path fill-rule="evenodd"
                  d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
        </svg>
    </button>

    {% include 'modal_search_department_employees.html' %}


{% endblock %}

app/templates/departments.html
{% extends 'base.html' %}
{% include 'navbar.html' %}

{% block content %}
<!--========FLEXBOX CONTAINER==========-->
<div class="flexbox_container">
    {% for department in departments %}
    <div class="flexbox_item">
        <a href="{{ url_for('site.department', dep_name=department['name']) }}"
           class="flexbox_inscription btn btn-lnk btn-sm">{{ department['name'] }}</a>
        <div class="flexbox_subscription">average salary: {{ department['average_salary'] }} $</div>

        <div class="flexbox_button">
            <a class="btn btn-outline-success btn-sm"
               data-toggle="modal" data-target="#modal_edit_department{{ department['id'] }}">Edit
            </a>
            <a href="{{ url_for('site.delete_department', dep_id=department['id']) }}"
               class="btn btn-outline-danger btn-sm"
               onclick="return confirm('Are you sure? The department will be deleted with all employees. ' +
                        'It is recommended to transfer all employees somewhere else first')">Delete</a>
        </div>
    </div>

    <!-- ====== MODAL EDIT DEPARTMENT ======= -->
    <div id="modal_edit_department{{ department['id'] }}" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Edit Department</h4>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('site.update_department', dep_id=department['id']) }}" method="POST">
                        <div class="form-group">
                            <label>Department Name:</label>
                            <input type="text" class="form-control" name="name" required="1"
                                   value="{{ department['name'] }}">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" id="btnEditDepartment" type="submit">Edit Department
                            </button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}


    <!-- 'ADD DEPARTMENT' FLEXBOX -->
    <a href='#' id="add_department_form_button" class="flexbox_item btn-lg btn-success" data-toggle="modal"
       data-target="#modal_add_department"
       style="justify-content: center; opacity: 0.5;">
        <div class="flexbox_inscription">
            <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-plus-square" fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                <path fill-rule="evenodd"
                      d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
            </svg>
        </div>
    </a>
</div>

<!-- ====== MODAL ADD DEPARTMENT ======= -->
<div id="modal_add_department" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Department</h4>
            </div>
            <div class="modal-body">
                <form action="" method="POST" id="AddDepartmentForm">
                    <div class="form-group">
                        <label>Department Name:</label>
                        <input type="text" class="form-control" name="name" required="1">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" id="btnAddDepartment" type="submit">
                            Add Department
                        </button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/templates/employee.html
{% extends 'base.html' %}
{% include 'navbar.html' %}

{% block content %}

    <!--========FLEXBOX CONTAINER==========-->
    <div class="flexbox_container">
        <div class="flexbox_item">
            <div class="flexbox_inscription">
                NAME
            </div>
            <div class="flexbox_subscription">
                {{ empl['name'] }}
            </div>
        </div>
        <div class="flexbox_item">
            <div class="flexbox_inscription">
                BIRTHDAY
            </div>
            <div class="flexbox_subscription">
                {{ empl['birthday'] }}
            </div>
        </div>
        <div class="flexbox_item">
            <div class="flexbox_inscription">
                SALARY
            </div>
            <div class="flexbox_subscription">
                {{ empl['salary'] }}$
            </div>
        </div>

        <!-- 'EDIT EMPLOYEE' FLEXBOX -->
        <a href="#" class="flexbox_item btn-lg btn-success" data-toggle="modal"
           data-target="#modal_edit_employee{{ empl['id'] }}"
           style="justify-content: center; opacity: 0.5;">
            <div class="flexbox_inscription btn-lg">
                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                </svg>
            </div>
        </a>

        <!-- 'DELETE EMPLOYEE' FLEXBOX -->
        <a href="{{ url_for('site.delete_employee', empl_id=empl['id']) }}" class="flexbox_item btn-lg btn-danger"
           data-toggle="modal" data-target="#modal_add_employee"
           style="justify-content: center; opacity: 0.5;"
           onclick="return confirm('Are you sure? All employee information will be deleted')">
            <div class=" flexbox_inscription btn-lg">
                <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor"
                     xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd"
                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
            </div>
        </a>
    </div>

    {% include 'modal_edit_employee.html' %}

{% endblock %}

app/templates/modal_add_employee.html
<!-- ====== MODAL ADD EMPLOYEE ======= -->
<div id="modal_add_employee" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Employee</h4>
            </div>
            <div class="modal-body">
                <form action="" method="POST">

                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" id="name" name="name" required="1">
                    </div>

                    <div class="form-group">
                        <label for="birthday">Birthday:</label>
                        <input type="date" class="form-control" id="birthday" name="birthday" required="1">
                    </div>

                    <div class="form-group">
                        <label for="salary">Salary:</label>
                        <input type="number" class="form-control" id="salary" name="salary" required="1">
                    </div>

                    <div class="form-group">
                        <label for="dep_name">Department:</label>
                        <select class="form-control" id="dep_name" name="dep_name">
                            {#                            current department will be selected by default#}
                            {% for department in departments %}
                                <option {% if department['name'] == title %}
                                    selected
                                {% endif %}>{{ department['name'] }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Add Employee</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/templates/modal_edit_employee.html
<!-- ====== MODAL EDIT EMPLOYEE ======= -->
<div id="modal_edit_employee{{ empl['id'] }}" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Edit Employee</h4>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('site.update_employee', empl_id=empl['id']) }}" method="POST">

                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" id="name" name="name" required="1"
                               value="{{ empl['name'] }}">
                    </div>

                    <div class="form-group">
                        <label for="birthday">Birthday:</label>
                        <input type="date" class="form-control" id="birthday" name="birthday" required="1" value="{{ empl['birthday'] }}">
                    </div>

                    <div class="form-group">
                        <label for="salary">Salary:</label>
                        <input type="number" class="form-control" id="salary" name="salary" required="1" value="{{ empl['salary'] }}">
                    </div>

                    <div class="form-group">
                        <label for="dep_name">Department:</label>
                        <select class="form-control" id="dep_name" name="dep_name">
                            {#                            current department will be selected by default#}
                            {% for department in departments %}
                                <option {% if department['name'] == dep_name %}
                                    selected
                                {% endif %}>{{ department['name'] }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Edit Employee</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

app/templates/modal_search_department_employees.html
<div class="modal fade" id="modal_search_department_employees" tabindex="-1" role="dialog"
     aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Search Department Employees by Birthday</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="Dates">
                    <div class="form-group">
                        <div class="row form-group">
                            <div class="col">
                                <label for="start_date">From:</label>
                                <input type="date" class="form-control" id="start_date" name="start_date"
                                       required="1">
                            </div>
                            <div class="col">
                                <label for="end_date">To:</label>
                                <input type="date" class="form-control" id="end_date" name="end_date" required="1">
                            </div>
                        </div>
                        <div class="form-group float-right">
                            <button class="btn btn-success" type="submit" id="SearchButton"
                                    onclick="searchEmployees(); return false;">Search
                            </button>
                        </div>
                    </div>

                </form>


                <table class="table table-hover table-striped">
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Birthday</th>
                        <th>Salary</th>
                    </tr>
                    <tbody id="EmployeesByDepartmentAndBirthday">

                    </tbody>
                </table>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>

    const searchButton = document.querySelector("#SearchButton");
    const start_date = document.querySelector("#start_date");
    const end_date = document.querySelector("#end_date");

    searchButton.addEventListener("click", () => {
        searchEmployees(start_date.value, end_date.value, onDataReceived);
    });

    let employeesByDepartmentAndBirthday = [];

    function searchEmployees(start_date, end_date, successCallback) {
        $.ajax({
            method: 'GET',
            url: `/api/search/{{ dep_id }}?start_date=${start_date}&end_date=${end_date}`,
            success: function (data) {
                successCallback(data);
            }
        })
    }

    function onDataReceived(response) {
        employeesByDepartmentAndBirthday = response
        buildTable(employeesByDepartmentAndBirthday)
        console.log(response)
    }

    function buildTable(data) {
        let table = document.getElementById('EmployeesByDepartmentAndBirthday')
        table.innerHTML = "" //clear table from previous search

        for (let i = 0; i < data.length; i++) {
            let row = `<tr>
                <td>${data[i].id}</td>
                <td>${data[i].name}</td>
                <td>${data[i].birthday}</td>
                <td>${data[i].salary}</td>
            </tr>`
            table.innerHTML += row
        }
    }


</script>

app/templates/navbar.html
<!--========DROPDOWN NAVBAR==========-->
  <div class="dropdown_navbar">
      <button class="dropdown_button" onclick="showContent()">
          {{ title }}
      </button>
      <div class="dropdown_content">
          {% if title != COMPANY_NAME %}
              <a href="{{ url_for('site.departments') }}"><i>===Main Page===</i></a>
          {% endif %}
          {% for department in departments if department['name'] != title %}
          <a href="{{ url_for('site.department', dep_name=department['name']) }}">
              {{ department['name'] }}
          </a>
          {% endfor %}
      </div>
  </div>
<script>
    function showContent() {
      let x = document.querySelector(".dropdown_content");

      if (!x.style.display || x.style.display === "none") {
        x.style.display = "block";
      } else {
        x.style.display = "none";
      }
}
</script>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissable" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">x</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}